### ISSUE TITLE
提交个PR过来吧

### ISSUE THREAD

**Issue by hiroi-sora** [OverflowCat/paddleocr#1]
https://github.com/hiroi-sora/PaddleOCR-json

如果此API已适配 `v1.3.0` ，麻烦再提个PR到我的仓库，谢谢~

**Comment by hiroi-sora** [comment]
Readme已添加此仓库链接。

**Comment by OverflowCat** [comment]
本来是想支持了 socket 方法再发版的，不过一直没时间做，今天暂且先把新版的文档补充了一下 😆
